[package]
name = "obs-streamable-auto-upload"
version = "0.1.0"
authors = ["SK <dev.umisk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "obs_streamable_auto_upload"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
dotenv = "0.15.0"
reqwest = {version = "0.11.0", features = ["multipart", "blocking"]}
obs-wrapper = { git = "https://github.com/Limeth/rust-obs-plugins" }
